amuletml.cabal, default.nix, src/Control/Monad/Infer.hs, src/Core/Optimise.hs, src/Core/Optimise/Match.hs, src/Data/Triple.hs, src/Data/VarSet.hs, src/Errors.hs, src/Parser.hs, src/Syntax.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Pattern.hs, src/Types/Unify.hs
Move to a pseudo-bidirectional type system algorithm, similar to the
one described for Damas-Milner inference in [0]. This isn't sound at
all, yet, particularly because of fiddlyness around the subsumption
check.b
We reuse most of the infrastructure, but the core judgement is
`Γ ⊢ x <= t` instead of `Γ ⊢ x => t` (i.e. checking instead of
synthesis).
You can recover inference from checking in a unification-based
system (like ours) like this:
```
infer e = do
x <- fresh
check e x
pure (e, x)
```
I've moved over both expression and pattern type inference (the two which used to suck the most) to the new bidirectional system, but kinds are pretty much the same.
=> Feature: Bidirectional(ish) inference

src/Core/Lower.hs, src/Core/Optimise/Inline.hs
Instead of guessing when things should be quantified, we can use the
fact that we statically know the types of everything to figure out
precisely when things should be quantified.
This does that.
=> Use type-directed lowering

src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Simplify.hs
This strips any let binding whose variable is not used in any live expression and whose value is pure. What qualifies as pure I hear you ask?
- Atoms (references, lambdas, literals)
- Partially applied functions
- Constructors
- Match expressions with one case (and no bindings are consumed)
- Binary operators
=> Some fancy dead code analysis

src/Parser.y, src/Syntax.hs, src/Syntax/Desugar.hs, src/Syntax/Pretty.hs, src/Syntax/Resolve.hs
This adds several extensions to the syntax of tuples:
- Any part of a tuple is optional, allowing for `(1, 2)`, `(1,)`, `(,)`, etc...
- Operator sections can be part of a tuple, so `(+1,1+,.access)` is now valid.
=> Add tuple sections

src/Backend/Compile.hs, src/Core/Core.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Newtype.hs, src/Core/Optimise/Reduce.hs, src/Core/Simplify.hs, src/Core/Types.hs
This PR adds terms of the form `x |> phi` where x is an atom and `phi` is a _coercion_. Coercions are a zero-cost way to witness an isomorphism between two types at compile time (which, (un)fortunately, the users can't exploit. yet.)
Coercions have one of the following forms:
- `a ~ b` relates the types `a` and `b`
- `dom phi`, where phi relates `a -> x` and `b -> y`, relates `a` and `b`
- `cod phi`, where phi relates `a -> x` and `b -> y`, relates `x` and `y`
Types of the form
```ocaml
type foo = Foo of a
```
become
```ocaml
type foo ...
let Foo x = (x |> a ~ foo)
```
Similarly, matching becomes matching on casts.
=> Feature: Coercions

amuletml.cabal, compiler/Test.hs, compiler/Test/Syntax/Gen.hs, compiler/Test/Types/Infer.hs, compiler/Test/Types/Util.hs, default.nix, src/Data/Spanned.hs, src/Types/Infer.hs
It'll eat our bugs. In the future. Things I learned from this:
1. Cabal was a mistake. No further comments.
2. The solver or type checker is _very_ slow, sometimes. Hedgehog has a knack for generating expressions that stress this, but using `Gen.small` tends to calm it down.
3. Generating counterexamples is hard.
Pls merge.
=> Test with Hedgehog

src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs
Pretty simple. Currently acts as a left-associative operator which binds more tightly than anything else. We can change later if it would make more sense.
=> Add backtick support to the lexer/parser

amuletml.cabal, src/Core/Core.hs, src/Core/Free.hs, src/Core/Occurrence.hs, src/Core/Optimise/Sinking.hs, src/Core/Simplify.hs
Almost 1/8th the size of GHC's equivalent, this sinks any pure expression down the tree to be as close to its use-site as possible, potentially reducing the number of allocations/operations which are required. For instance, this'll reduce:
```ml
let main x = let y = (1, x)
in match x with
| Nil -> fun _ -> y
| _ -> fun x -> (x, Nil)
```
into
```ml
let main x = match x with
| Nil -> let y = (1, x)
in fun _ -> y
| _ -> fun x -> (x, Nil)
```
There are definitely some enhancements we could make to this (such as duplicating trivial expressions across matches or considering partially applied functions as "pure"), but this'll do for now.
=> Add an allocation sinking pass

src/Parser.y
Now, it's admissible to use a non-empty, comma-separated list of
expressions as both the scrutinee and pattern in a Match:
match x, ..., y with
| p, ..., p' -> ...
is equivalent to
match (x, ..., y) with
| (p, ..., p') -> ...
=> Add implicit tuples in matches

src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs
It's a hack. It's allowed to be impredicative, because it's not even a
thing in the abstract syntax: `f @@ x y` _parses the same as_ `f (x y)`.
Not _desugars to_ `f (x y)`, mind you: we do it in the parser.
=> Add an application operator, @@

examples/gadt/equality.ml, src/Core/Core.hs, src/Core/Lower.hs, src/Core/Optimise.hs, src/Core/Optimise/Reduce.hs, src/Syntax.hs, src/Syntax/Pretty.hs, src/Syntax/Raise.hs, src/Syntax/Subst.hs, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Unify.hs
Except for the η-expansion associated with subsumption constraints, coercions now represent the steps that the solver took to make two types equal.
=> Generate Correct Evidence

src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs, src/Syntax.hs, src/Syntax/Desugar.hs, src/Syntax/Pretty.hs, src/Syntax/Raise.hs, src/Syntax/Resolve.hs, src/Syntax/Transform.hs
This evaluates the expression within the scope of a module. Some examples:
```ml
module X = begin
let a = 1
and b = 2
end ;;
let main = begin
X.a; (* As before, just a module index *)
X.(a, b) (* Constructs a tuple of (X.a, X.b) *)
X.(a + b) (* Evaluates X.a + X.b *)
X.{ a = a } (* Evaluates { a = X.a } *)
end
```
This also changes the syntax for "import as" from `open X as Y` to `module Y = X`.
=> Add support for an "open in" construct

amuletml.cabal, compiler/Main.hs, compiler/Test/Core/Lint.hs, src/Backend/Compile.hs, src/Core/Arity.hs, src/Core/Builtin.hs, src/Core/Core.hs, src/Core/Free.hs, src/Core/Lint.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Joinify.hs, src/Core/Optimise/Newtype.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Sinking.hs, src/Core/Simplify.hs, src/Core/Types.hs, src/Core/Var.hs, src/Data/VarMap.hs, src/Data/VarSet.hs
This allows us to attach additional annotations to variables in the future. Namely the arity of join points.
Variables are also tagged with their type (type, tyvar, value, coercion), which we might want to verify in core at a later date - not currently a priority however.
=> Use a specialised variable type for core

compiler/Errors.hs, compiler/Test/Types/Check.hs, src/Control/Monad/Infer.hs, src/Types/Infer.hs, src/Types/Unify.hs, tests/types/fail_skolem_poly.out
While type checking depends on the structure of the code, solving is mostly independent (other than the tree structured imposed by implication constraints).
It's also _mostly_ independent of order: we can keep solving constraints, even after one fails.
This patch does just that - try to solve _all_ constraints, and then report all errors that arose.
=> Report Many Type Errors

src/Core/Builtin.hs, src/Core/Lower.hs, src/Syntax.hs, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Unify.hs, tests/lua/match_multi.lua, tests/rankn/tuple01-pass.ml, tests/rankn/tuple01-pass.out, tests/rankn/tuple02-fail.ml, tests/rankn/tuple02-fail.out
This adds Amulet's first two wired-in names with unfoldings, `fst#`
(-32) and `snd#` (-33). The GHC-inspired magic hash is there to indicate
magic; These bindings are not user accessible and are basically only
added by the type checker.
`fst#` and `snd#` are used to re-build tuples at use sites that impose
subsumption constraints. Consider we need to solve
"('a * 'b) <= ('c * 'd)"
We start by decomposing these into
'c <= 'a (call this wrapper α)
'd <= 'b (call this wrapper β)
Then, we re-build the tuple (call it x, with ξ fresh) like so:
let ξ = x (* to prevent reevaluation *) in
(α[fst ξ], β[fst ξ])
where `w[e]` means applying `w` to `e`.
Moreover, WrapConts now have an explanation for better pretty printing.
Though not much.
This commit also fixes a long-standing bug where some …
=> Componentwise Tuple Subsumption

compiler/Repl/Display.hs, src/Backend/Lua/Postprocess.hs, src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs, src/Syntax.hs, src/Syntax/Desugar.hs, src/Syntax/Pretty.hs, src/Syntax/Resolve.hs, src/Syntax/Transform.hs, tests/lazy/lazy01-pass.ml, tests/lazy/lazy02-fail.ml, tests/lazy/lazy02-fail.out, tests/lazy/lazy04-pass.ml, tests/lazy/lazy04-pass.out, tests/parser/fail_span.out
Sometimes, the automatic thunking just doesn't work out. E.g.:
```
(* error : forall 'a. string -> 'a *)
error "foo" : lazy int
```
generates the constraints
```
string ~ string
'a <= lazy int
```
and this becomes `error {lazy int} "foo".`
Typing `lazy (fun () -> ...)` is a lot of work, so this makes it easier.
=> Make 'lazy' a keyword

amuletml.cabal, src/Core/Optimise/Newtype.hs, src/Core/Simplify.hs, tests/lua/newtype.lua, tests/lua/newtype.ml
Newtype optimisation is back! Now with, hopefully, 100% less broken Core
Lints. I've added a small test about how newtypes are _compiled_ (this
is likely to break in the future if we ever manage to inline
constructors, by the way).
This optimisation is unreasonably efficient in Amulet, considering that
all types with a single constructor (and no existentials) are eligible
for newtype elimination, considering we have no curried constructors.
This includes single-constructor GADTs, since evidence parameters are
currently erased during Lower.
The idea is the same as before: we turn a type like
```ocaml
type foo 'a {
Foo : forall ('a : *). 'a -> foo 'a
}
```
into a worker like
```ocaml
type foo 'a {}
let Foo : forall ('a : *). 'a -> foo 'a =
Λ ('a : *). λ(x : 'a). x |> 'a ~ foo 'a
```
which …
=> New-type elimination (again)

compiler/Repl.hs
The existential example doesn't work in the REPL because of this:
```
> type box =
.   | Box : ('a -> string) * 'a -> box ;;
> let show_it (Box (f, x)) = f x
amc: src/Core/Optimise/Reduce.hs:384:9-50: Irrefutable pattern failed for pattern Just ty
```
@zardyh told me to do this to make Amulet seem like it has contributors.
=> Don't run the reduce pass in the REPL

src/Backend/Lua/Postprocess.hs
Before:
```
> let pi = lazy (abs (atan (0.0 -. 1.0)) *. 4.0)
pi : lazy float =
lazy <function>
> force pi
[string "do..."]:6: Pattern matching failure at =stdin[1:10 ..1:46] (ErrRun)
> 
```
After:
```
> let pi = lazy (abs (atan (0.0 -. 1.0)) *. 4.0)
pi : lazy float = lazy <function>
> force pi
_ : float = 3.141592653589793
> 
```
=> Fix a pattern matching failure when using `force` in the REPL

src/Syntax/Types.hs, src/Types/Infer.hs, tests/types/implicits/modules-fail.ml, tests/types/implicits/modules-fail.out, tests/types/implicits/modules-pass.ml, tests/types/implicits/modules-pass.out
This simply holds a mapping from module names to implicit scopes, with opening looking up the appropriate module and merging it with the current one.
=> Allow open to import implicits into scope

src/Backend/Lua/Emit.hs, src/Backend/Lua/Postprocess.hs, src/Backend/Lua/Syntax.hs, src/Core/Arity.hs, src/Core/Builtin.hs, src/Core/Core.hs, src/Core/Free.hs, src/Core/Lint.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Joinify.hs, src/Core/Optimise/Newtype.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Sinking.hs, src/Core/Types.hs, src/Types/Infer.hs, tests/lua/arithmetic.lua, tests/lua/match_consumed.lua, tests/lua/section.lua, tests/lua/stream.lua
It's almost midnight - I'm afraid I don't have energy to write a fancy commit message. Needless to say, the implementation is a little grim.
This implementation is intentionally very basic and restrictive:
- Unboxed tuples can only (currently) appear on the left hand side of an arrow type. They cannot be returned.
- We do not do any worker/wrapper transformation beyond binops within lower.
- Codegen is probably broken.
This mainly intends to serve as a POC and a starting point for the codegen rewrite.
=> Unboxed tuples: Part 1

src/Core/Lint.hs, src/Syntax/Resolve.hs, src/Types/Infer.hs, src/Types/Unify.hs
I want to die.
This changes the typing rules (semantics?) of `{ x with r = e }` to be extension
of `x` to contain `r` but rather (monomorphic) update of `x`.
=> Feature: Record Updates

examples/gadt/vector.ml, src/Backend/Lua/Emit.hs, src/Core/Arity.hs, src/Core/Builtin.hs, src/Core/Lower.hs, src/Core/Optimise/Reduce.hs, src/Syntax/Resolve/Scope.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Outline.hs, tests/lua/and.lua, tests/lua/and.ml
These are not technically compiled correctly anyway (they are lazy when they should not be), so it would be better to handle this within the codegen.
That being said, the currently produced code is somewhat terrible: we need to eliminate lazy/force pairing and be smart about detecting such combinations of if/else blocks.
Note that this still keeps the operator precedence rules for `&&` and `||`.
=> Remove boolean operators

src/Backend/Lua/Emit.hs, src/Core/Arity.hs, src/Core/Core.hs, src/Core/Free.hs, src/Core/Lint.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Joinify.hs, src/Core/Optimise/Newtype.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Sinking.hs, src/Core/Types.hs, tests/lua/and.lua, tests/lua/match_consumed.lua, tests/lua/newtype.lua, tests/lua/section.lua, tests/lua/stream.lua
There are several reasons for this
- It is easier to generate code for term lambdas, as they can contain arbitrary statements.
- It is easier to pattern match on variables containing lambdas, as they will be stored as a separate variable.
- Atoms no longer contain code - they are simply made up of references and literals - thus some handling of them can be simplified.
=> Make lambdas terms rather than atoms

amuletml.cabal, compiler/Test/Core/Lint.hs, src/Core/Core.hs, src/Core/Lint.hs, src/Core/Simplify.hs, src/Text/Pretty/Annotation.hs
- Use applicatives instead of monads where possible, meaning a larger number of errors are accumulated.
- Annotate the terms with errors, instead of building a list. This means we can report errors closer to their original location and hopefully make dumps easier to digest.
- Provide the last pass to be run inside the error message. We could also modify this to include the program _before_ lint was run.
It's a long way from perfect, but hopefully it'll make it easier next time we hit a problem.
The diff is a little noisy as I shifted some checks into the top level, with the aim to make the term checks slightly less dense. Sorry! This would have been much simpler if `ApplicativeDo` handled more cases (or we'd just done a `MonadWriter (CoreErrors a) m`), but alas.
=> Rewrite core lint

amuletml.cabal, default.nix, src/Core/Core.hs, src/Core/Occurrence.hs, src/Core/Optimise/CommonExpElim.hs, src/Core/Simplify.hs, src/Core/Var.hs, src/Data/VarMap.hs, src/Data/VarSet.hs, tests/lua/cse.lua, tests/lua/cse.ml
Pretty simple: We have a hashmap connecting expressions to their binding
sites, which we can use to increase sharing of pure variables.
For instance:
```ocaml
let x = Foo 1 in
let y = Foo 1 in
use x y
```
since x and y's values end up hashing to the same thing, we can
substitute all uses of y (since it's considered later) with a reference
to x, and generate
```ocaml
let x = Foo 1 in
use x x
```
=> Add a CSE pass

amuletml.cabal, compiler/Main.hs, compiler/Repl.hs, src/Backend/Escape.hs, src/Backend/Lua.hs, src/Backend/Lua/Emit.hs, src/Data/VarMap.hs, src/Data/VarSet.hs, src/Text/Dot.hs, tests/lua/and.lua, tests/lua/arithmetic.lua, tests/lua/begin_wrapper.lua, tests/lua/cse.lua, tests/lua/escape.lua, tests/lua/function_order.lua, tests/lua/if.lua, tests/lua/let_pattern.lua, tests/lua/let_pattern_partial.lua, tests/lua/match_consumed.lua, tests/lua/match_multi.lua, tests/lua/newtype.lua, tests/lua/pattern_multiple_consume.lua, tests/lua/pattern_multiple_consume.ml, tests/lua/record_extend.lua, tests/lua/reduce_single_constructor.lua, tests/lua/section.lua, tests/lua/stream.lua, tests/lua/tuple_literal.lua
The previous version of the codegen operated on the concept of an expression "stack". We'd push new variables onto the stack, and pop them when they were consumed. If a variable did note match up, we'd convert the entire stack into local variables, to ensure that the order of side effects was preserved.
While this worked well for unprocessed inputs, the optimiser would often reorder terms in such a way that the codegen would flush bindings more often than needed, meaning we'd generate rather silly Lua.
This rewritten codegen handles execution order via a graph instead. We walk down the spine of let expressions, and gather expressions and their dependencies (free variables and the preceding impure expression).
Expressions which are only used once can be embedded inline as long as doing so …
=> Rewrite the Lua codegen

src/Backend/Lua/Syntax.hs, tests/lua/and.lua, tests/lua/arithmetic.lua, tests/lua/begin_wrapper.lua, tests/lua/cse.lua, tests/lua/escape.lua, tests/lua/function_order.lua, tests/lua/if.lua, tests/lua/let_pattern.lua, tests/lua/let_pattern_partial.lua, tests/lua/match_consumed.lua, tests/lua/match_multi.lua, tests/lua/newtype.lua, tests/lua/pattern_multiple_consume.lua, tests/lua/record_extend.lua, tests/lua/reduce_single_constructor.lua, tests/lua/section.lua, tests/lua/stream.lua, tests/lua/tuple_literal.lua
- Handle "array entries" within Lua tables, so we can pretty print `{ 1, 2, 3 }` correctly.
- `group` some expressions, allowing them to be emitted on one line. We currently do this to simple functions (only a return) and tables.
=> Rework the Lua pretty printer a little

.gitignore, amuletml.cabal, compiler/Main.hs, compiler/Repl.hs, default.nix, src/Backend/Lua.hs, src/Backend/Lua/Emit.hs, src/Backend/Lua/Postprocess.hs, src/Language/Lua/Parser/Error.hs, src/Language/Lua/Parser/Lexer.x, src/Language/Lua/Parser/Parser.y, src/Language/Lua/Parser/Token.hs, src/Language/Lua/Parser/Wrapper.hs, src/Language/Lua/Quote.hs, src/Language/Lua/Syntax.hs, tests/lua/and.lua, tests/lua/match_consumed.lua
This adds a couple of things:
- A parser for a subset of Lua. Our `Language.Lua.Syntax` data structures are missing a couple of things (namely `not`, `-`, `local function` and `foo:bar()`) so we do not yet parse those.
- A Template Haskell quasi-quoter for Lua expressions and statements. One can use `$foo` to substitute variables, `%foo` for expressions and `@foo` for statements.
- Replaces some of the more complex expressions in `Backend.Lua.Postprocess` with their quasi-quoted alternatives.
=> Lua quasi-quoter

src/Backend/Lua/Emit.hs, src/Core/Lower.hs, tests/lua/external.lua
This allows more optimisation opportunities. In the future, when annotations are added to the syntax, we will be able to handle how these are lowered more granularly.
=> Convert native definitions to use unboxed tuples within Lower

src/Core/Optimise.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Reduce/Base.hs, src/Core/Optimise/Reduce/Inline.hs, src/Core/Simplify.hs, src/Data/VarMap.hs, src/Data/VarSet.hs, tests/lua/as_pattern.lua, tests/lua/cse.lua, tests/lua/let_pattern.lua, tests/lua/match_heuristic.lua, tests/lua/opt_inline_tyapp.lua, tests/lua/opt_inline_tyapp.ml, tests/lua/optimise_sink.lua, tests/lua/precedence.lua
- Keep track of the "usage context" for deferred applications.
- Try to be a little smarter about when we inline:
- Always inline when the definition is smaller than the application itself
- Never inline if all arguments are unknown, and the function isn't used anywhere interesting.
- Otherwise compare the body size minus some discounts to the threshold. Here the discounts are "Known argument which is applied/matched on" and "known result which is applied/matched on".
We need to do a lot of fine-tuning of the heurstic and definition scores to ensure this is actually effective. There's definitely some values here which are rather off.
As always, [largely based on this paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2002/07/inline.pdf).
=> Reducer rewrite 3: Inliner heurstics

amuletml.cabal, compiler/Debug.hs, compiler/Main.hs, compiler/Repl.hs, default.nix
I'd like to add support for reloading files before finishing this off, but there's a coupel of questions worth resolving:
- Should using `:load` reset the environment. This is useful, as there won't be artifacts from previous `:load`s.
- If we do reset the environment, how does one load multiple files? One possibility would be to specify multiple files to `:load`. Obviously the whole module resolution thing is a whole 'nother discussion, but...
- How should `:reload` handle file order (if we don't have variadic load)?
=> REPL file loading

examples/amulet-logo.ml, src/Control/Monad/Infer.hs, src/Data/Reason.hs, src/Parser.y, src/Syntax.hs, src/Syntax/Pretty.hs, src/Syntax/Resolve.hs, src/Syntax/Resolve/Toplevel.hs, src/Syntax/Types.hs, src/Types/Infer/Class.hs, src/Types/Kinds.hs, tests/lua/default-method.lua, tests/lua/default-method.ml, tests/lua/monoid.lua, tests/parser/pass_class.ml, tests/parser/pass_class.out, tests/resolve/pass_class.ml, tests/resolve/pass_class.out, tests/types/class/default01.ml, tests/types/class/default01.out, tests/types/class/default02-fail.ml, tests/types/class/default02-fail.out, tests/types/class/default03.ml, tests/types/class/default03.out
Pretty self-explanatory: Default implementations for a method in the body of the class itself.
For _instance_ (ba dum tss):
```ocaml
class eq 'a begin
val (==) : 'a -> 'a -> bool
val (<>) : 'a -> 'a -> bool
let x <> y = not (x == y)
let x == y = not (x <> y)
end
```
This class can be implemented by either implementing...
- both `(==)` and `(<>)`, or
- just `(==)`, or
- just `(<>)`.
=> Default Methods

compiler/Repl.hs, compiler/Test/Syntax/Gen.hs, compiler/Test/Types/Util.hs, src/Control/Monad/Infer.hs, src/Core/Lower.hs, src/Core/Lower/Basic.hs, src/Core/Lower/Pattern.hs, src/Syntax.hs, src/Syntax/Types.hs, src/Syntax/Var.hs, src/Syntax/Verify.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Class.hs, src/Types/Infer/Constructor.hs, src/Types/Infer/Outline.hs, src/Types/Infer/Pattern.hs, src/Types/Kinds.hs, src/Types/Unify.hs
This allows us to add additional phrases between resolving and lowering without having to wrap the variable each time.
=> Convert Var to a type family rather than data family

compiler/Test/Core/Backend.hs, compiler/Test/Syntax/Resolve.hs, compiler/Test/Syntax/Verify.hs, compiler/Test/Types/Check.hs, compiler/Test/Util.hs, src/Control/Monad/Infer.hs, src/Control/Monad/Namey.hs, src/Core/Lower/Pattern.hs, src/Core/Optimise.hs, src/Core/Optimise/Newtype.hs, src/Syntax/Desugar.hs, src/Syntax/Resolve.hs, src/Types/Infer.hs, src/Types/Infer/Class.hs, src/Types/Infer/Constructor.hs, src/Types/Kinds.hs, src/Types/Unify.hs
This means we have to make several patterns unconditional (by adding `~`). On the flip side, it means we're a little more explicit on what is meant to be a complete pattern and what is not.
There are several reasons for this:
- Generating fresh names has little to do whether the current monad can fail.
- Using `runNameyT` inside a monad transformer requires that the parent transformer has a `MoandFail` instance, which can get a little annoying.
=>  Remove the MonadFail constraint from MonadNamey

Jenkinsfile, amuletml.cabal, compiler/Test.hs, compiler/Test/Reporter.hs
As the commit message says. Mostly inspired by every other test runner I've ever written:
- Displays dots as the tests progress.
- By default only shows failing tests/groups, though there are flags to make it more verbose (`--display t`, `--display g`).
Failures look like this:
Successes look like this:
=> Rewrite the test reporter to be less verbose and more sexy

amuletml.cabal, compiler/Test.hs, compiler/Test/Options.hs, compiler/Test/Reporter.hs, compiler/Test/Rerun.hs, default.nix
This simply writes the result of the last test execution to `dist-newstyle/.rerun`. Passing `-R` will cause only the failing tests to be re-executed.
=> Add flag to rerun tests

src/Core/Lower.hs, src/Core/Lower/Basic.hs, src/Parser.y, src/Syntax/Desugar.hs, src/Syntax/Resolve.hs, src/Syntax/Resolve/Toplevel.hs, src/Syntax/Toplevel.hs, src/Syntax/Verify/Pattern.hs, src/Types/Infer.hs, src/Types/Infer/Class.hs, tests/types/gadt/gadt01.out, tests/verify/pmcheck/empty_match_01.ml, tests/verify/pmcheck/empty_match_01.out, tests/verify/pmcheck/empty_match_02.ml, tests/verify/pmcheck/empty_match_02.out
This allows us to distinguish abstract types from concrete ones with no inhabitants:
```ml
type abstract
type void = |
```
We also update the totality checker to handle this, meaning we can finally fix several false-positives.
=> Add an explicit syntax for empty variants

.gitignore, compiler/Test/Core/Backend.hs, src/Backend/Lua/Emit.hs, src/Text/Pretty.hs, tests/lua_no_opt/function-order-01.lua, tests/lua_no_opt/function-order-01.ml, tests/lua_no_opt/function-order-02.lua, tests/lua_no_opt/function-order-02.ml
Will fix #163 at some point, currently only fixes on of the edge cases.
The current issue here is that impure nodes may get merged into pure ones. As a result, we break the ordering invariant, as any dependencies on this impure node are dropped.
This attempts to fix this, by introducing a "consumed" node, which simply says "we've been merged into another node", and so any dependencies on the merged node, now depend on the parent.
There's still two test cases which are not functioning quite how they should:
- `stream.lua` - the introduction of the consumed node now means that the loop has a graph.
- `function-order-02.lua` - this is the bug mentioned in #163. I haven't introduced any logic for this yet - I'm not 100% sure how to fix this properly yet, though have some ideas.
```diff
diff …
```
=> Preserve term ordering invariants

compiler/Errors.hs, examples/pipe.ml, src/Core/Core.hs, src/Data/Reason.hs, src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs, src/Syntax/Desugar.hs, src/Syntax/Expr.hs, src/Syntax/Expr/Instances.hs, src/Syntax/Let.hs, src/Syntax/Resolve.hs, src/Syntax/Transform.hs, src/Syntax/Value.hs, src/Syntax/Verify.hs, tests/lua/emit_ifs.ml, tests/lua/list.lua, tests/lua/stream-zip.ml, tests/lua/stream.ml, tests/parser/fail_pattern_guard.out, tests/types/idioms.ml, tests/types/idioms.out
`(| f x y z |)` = `pure f <*> x <*> y <*> z`; Like `begin`-expressions, uses whatever `pure` and `<*>` are in scope.
=> Add idiom brackets

compiler/Main.hs, compiler/Repl.hs, src/Control/Monad/Chronicles.hs, src/Frontend/Driver.hs, src/Frontend/Errors.hs, src/Syntax/Resolve/Error.hs
I was going to do the prelude loading in the same changset, and then realised I should probably get on with some uni work. So here goes for now... 
---
- Abandon our approach of only trying to show new errors - most of the
time, it's actually more useful to provide every error available.
This does mean that warnings will show up each time a user imports a
file multiple times within the REPL, but I hope that's rare enough
that this ends up being a satisfactory fix.
Closes #189
- Both the emitted core and errors are now gathered with a depth-first
seach over the dependency graph. This hopefully simplifies things a
little.
- Don't crash when a module is missing, instead just return 'Nothing' -
while we were correctly handling missing files within 'importModule',
they'd still be added to the …
=> Lots of minor improvements to the module system

compiler/Main.hs, compiler/Repl.hs
Effectively defines three sub-command: `compile`, `repl` and `connect` (defaulting to `repl`), rather than switching based on what combination of input files, `--repl` and `--client` were specified.
Hopefully this makes the `optparse-applicative` code a little easier to understand too.
<details>
<summary>Command overview</summary>
```
λ :main --help
Usage: <interactive> [COMMAND] [-v|--version]
The Amulet compiler and REPL, version 0.4.0.0 (053fcfd)
Available options:
-h,--help                Show this help text
-v,--version             Show version information
Available commands:
compile                  Compile an Amulet file to Lua.
repl                     Launch the Amulet REPL.
connect                  Connect to an already running REPL instance.
λ :main compile --help
Usage: …
```
=> Switch the argument parser to be sub-command based

.travis.yml, examples/mini-servant.ml, repl.sh, src/Control/Monad/Infer.hs, src/Types/Infer.hs, src/Types/Infer/Class.hs, src/Types/Unify.hs, tests/driver/Test/Types/Check.hs, tests/lint/shadow_forall.ml, tests/lua/section.lua, tests/lua/section.ml, tests/types/begin05.ml, tests/types/begin05.out, tests/types/fail_value_restriction.ml, tests/types/fail_value_restriction2.ml, tests/types/fail_value_restriction2.out, tests/types/unify.ml
I recently found a couple of code examples which really should have failed core lint, but didn't. Attempting to fix that yielded something more worrying: we have several TC tests which don't pass core lint currently, including two which don't appear to terminate.
This is a (painful) attempt at trying to squash those bugs, and hopefully get core lint in a more robust shape.
```
Expected type ->#t-7 (int#t-2 -> int#t-2) -> {_1 : int#t-2, _2 : int#t-2} -> {_1 : int#t-2, _2 : int#t-2}
got type (int#t-2 -> int#t-2) -> {_1 : int#t-2, _2 : int#t-2} -> {_1 : int#t-2, _2 : int#t-2}
=> Lower and Lint bug blitz

bin/Amc.hs, bin/Amc/Repl.hs, bin/GenExample.hs, src/Control/Monad/Infer.hs, src/Core/Simplify.hs, src/Frontend/Driver.hs, tests/amc/files/import.ml, tests/amc/files/use_prelude.ml, tests/amc/lib/my_lib.ml, tests/amc/lib/prelude.ml, tests/amc/path.t, tests/amc/prelude.t, tests/amc/usage.t, tests/driver/Test/Core/Backend.hs, tests/driver/Test/Core/Lint.hs, tests/driver/Test/Syntax/Resolve.hs, tests/driver/Test/Types/Check.hs
- Disable core lint by default, requiring users to run with `--core-lint` instead.
- Allow running starting the REPL with a custom prelude (`--prelude`) or no prelude (`--no-prelude`). 
- Move library paths to a "driver config", rather than extending an environment variable.
=> Tiny module-system and CLI improvements

repl.sh, src/Core/Lower.hs, src/Parser.y, src/Parser/Lexer.x, src/Parser/Token.hs, src/Syntax/Desugar.hs, src/Syntax/Resolve.hs, src/Syntax/Toplevel.hs, src/Syntax/Verify.hs, src/Types/Infer.hs, tests/resolve/pass_include.ml, tests/resolve/pass_include.out
`include` is exactly as `open` except the signature of the included module is concatenated with the signature of the including module. Concretely:
```ocaml
module X : sig val x : int end = begin
let x = 1
end
module Y = (begin
let y = 1
include X
end) : sig
val x : int
val y : int
end
```
=> Feature: 'include' statement

amuletml.cabal, bin/Amc.hs, bin/Amc/Repl.hs, bin/GenExample.hs, src/Frontend/Driver.hs
This implements the design as discussed in #183:
- The driver now has a "clock", with a major and minor counter.
- Counters are used to mark places where we expect loaded files to change. Otherwise you may have a file change between a call to `getSignature` and `getLowered`, which is terribly confusing.
- Ticks (minor updates), allow non-emitted files to be reloaded if they have changed. This means you can reimport erroring files within the repl, and we will attempt recompilation.
- Tocks (major updates), reloads any changed file. This is only done when using `:[re]load`, as you need to throw away any existing values at the same time.
- The REPL now keeps the same driver around for the whole session, ticking and tocking it where appropriate.
- Files are considered to have changed if their …
=> Module caching

amuletml.cabal, bin/Amc.hs, bin/Amc/Compile.hs, tests/amc/usage.t
One may now run `amc compile test.ml --watch -o out.lua`, and it will recompile whenever `test.ml`, or any of its dependencies change. File watchers on dependencies are automatically registered/unregistered.
Note, there's currently a few places where there is room for improvement:
- This currently has no additional debouncing (beyond what is done within fsnotify). I did think about adding some, but found I didn't really need any quite yet.
- Related to that, this will run compilation to completion. Ideally we would cancel compilation if files changed during it, and restart (while still keeping as much progress as possible).
- Most time is currently spent in the optimiser. It'd be nice to have per-module optimisations, but there's a _lot_ of plumbing needed to get to that stage.
=> Add a basic watch mode for compilation

src/Syntax/Resolve.hs, src/Syntax/Types.hs, src/Syntax/Verify.hs, src/Types/Infer.hs, tests/resolve/pass_include.out, tests/resolve/pass_modules.out, tests/types/class/assoc-eta.out, tests/types/letopen.out, tests/types/scope.ml, tests/types/scope.out
And, indeed, unqualify names when leaving a module. In practice, this
means that the entire TC scope consists of types that are writable, as
printed, in the scope they are referring to. This fixes:
1. Printing of types in error messages
2. Suggestions offered by ~~amuse~~ `Types.Holes`
=> Qualify names when leaving a module

amuletml.cabal, bin/Amc.hs, bin/Amc/Compile.hs, bin/Amc/Compile/Raw.hs, bin/Amc/Compile/Shim.hs, src/Text/Pretty/Semantic.hs, tests/amc/usage.t, tools/deploy-build.sh
We generate Lua code as usual, then put that in a C file together with
some glue code to call the Lua interpreter (or LuaJIT).
We get to have our cake and eat it too!
This was inspired by [luastatic](https://github.com/ers35/luastatic).
=> Feature: "Lua static" backend

amuletml.cabal, bin/Amc/Repl.hs, src/Backend/EmitGraph.hs, src/Backend/Lua/Emit.hs, src/Backend/Scheme.hs, src/Core/Arity.hs, src/Core/Builtin.hs, src/Core/Core.hs, src/Core/Free.hs, src/Core/Lint.hs, src/Core/Lower.hs, src/Core/Lower/Basic.hs, src/Core/Lower/Pattern.hs, src/Core/Lower/TypeRepr.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/CommonExpElim.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Reduce/Base.hs, src/Core/Optimise/Reduce/Inline.hs, src/Core/Optimise/Reduce/Pattern.hs, src/Core/Optimise/Sinking.hs, src/Core/Optimise/Uncurry.hs, src/Core/Types.hs
This simply moves the "emit graph" code into a separate module, which should allow us to more easily implement other backends which generate syntax trees (such as a JS backend, or improving the Scheme one).
In order to define a new backend, one creates an empty data type `Foo`, and defines an instance `Emitter Foo`, which determines the type of statements and expressions within the syntax, as well as how to create such terms. This is then used to build up a partial ordering of statements/expressions, and stitch them together when emitting a function.
This simplifies the Lua backend a little (reduces it by ~300 loc), though it's still annoyingly large.
We also make Core a little less polymorphic: Types, coercions and atoms are no longer polymorphic in their variable - they always store …
=> Abstract out Backend.Lua.Emit's graph handling

amuletml.cabal, src/Core/Optimise.hs, src/Core/Optimise/SAT.hs, src/Core/Simplify.hs, tests/lua/monoid.lua, tests/lua/nested_match.lua, tests/lua/nested_match_basic.lua, tests/lua/opt_sat.lua, tests/lua/opt_sat.ml, tests/lua/opt_sat_unsat.lua, tests/lua/opt_sat_unsat.ml, tests/lua/pattern_guard.lua
The idea of the SAT as an
optimisation is to reduce the number of arguments that must be passed to
a recursive function, and, subsequently, the argument shuffling noise.
Example:
let map @a @b (f : a -> b) (xs : list a -> list b) =
match xs with
| [] -> [] @a
| Cons (x, xs) ->
let x = f x
let xs = map @a @b f xs
Cons (x, xs)
Here, the recursive call to map is always made with the same arguments
`@a`, `@b`, `f` and `xs`. We call these the "static arguments" of map.
We can lift them out of the recursive path:
let map @a @b (f : a -> b) =
let rec map_sat (xs : list a -> list b) =
let map_shadow @a @b (f : a -> b) (xs : list a -> list b) =
map_sat xs
match xs with
| [] -> [] @a
| Cons (x, xs) ->
let x = f x
let xs = map_shadow @a @b f xs
Cons (x, xs)
map_sat
Then, the shadow can inline:
let …
=> Implement the "Static Argument" transformation

bin/Amc/Repl.hs, bin/Amc/Repl/Command.hs, tests/amc/prelude.t
This PR adds a `:help` / `:?` command that displays what each command does.
When starting the REPL, this fact is also displayed.
This would help new users get a hang of the REPL and the available commands.
=> Add :help REPL command with explanations of every command

bin/Amc.hs, bin/Amc/Compile.hs, src/Frontend/Errors.hs, tests/amc/usage.t
We currently support the following flags:
- `-Werror` (error on all warnings/notes)
- `-Wno-error` (disable erroring on warnings)
- `-Werror=3002` (always error on 3002)
- `-Wno-error=3002` (don't error on 3002, if 3002 is normally a warning/note).
Note that these flags are applied in order, so `-Werror -Wno-error` will do nothing.
Ideally we'd also support error names, as this doesn't allow you to error on messages without codes, but it's a good start.
Closes #228.
=> Add support for -Werror and friends

.gitignore, amuletml.cabal, bin/Amc/Compile/Raw.hs, bin/Amc/Compile/Shim.c, bin/Amc/Compile/Shim.hs
This hopefully prevents the pre-processor incorrectly trying to do anything with the raw string within the Haskell file.
=> Move the C shim into a separate file

lib/data/stream.ml, lib/prelude.ml
```ocaml
let primes =
let open Seq in
let rec sieve p =
let (p, xs) = from_option (lazy (error "wasn't infinite")) (uncons p)
p :> lazy (xs |> filter ((> 0) % flip mod p) |> sieve)
sieve (arithmetic_seq 2 3)
let factor i =
let rec go acc primes i =
match i, Seq.uncons primes with
| 1, _  -> acc
| p, None -> p :: acc
| i, Some (p, _) when i `mod` p == 0 ->
go (p :: acc) primes (i // p)
| i, Some (_, ps) -> go acc ps i
go [] (primes |> Seq.take_while (fun p -> p <= int_of_float (i / 2))) i
```
=> add a library of stream functions

tools/deploy-build.sh
Intended as a more long-term and less breaky version of 4eeba0c53ca213ac191c3b6f90f6320834a7b92b. This removes any messing around with the `.stack-work` directory, and just makes Stack copy the binaries into the `result/` directory.
While this does mean that UPX will minify all binary files, rather than just ones copied on the command line, I don't think that's a serious problem. That said, should be easy enough to install into a temporary directory and copy from there if preferred.
=> Use stack install to copy binary files

amuletml.cabal, bin/Amc.hs, bin/AmuletLsp/Worker.hs, src/Frontend/Driver.hs, src/Frontend/Files.hs, src/Syntax/Resolve.hs, src/Syntax/Resolve/Error.hs, src/Syntax/Resolve/Import.hs, tests/amc/path.t, tests/driver/Test/Syntax/Resolve.hs, tests/resolve/fail_import_abandon.out, tests/resolve/fail_import_not_found.out, tests/resolve/fail_import_not_found_path.out
- Importers now return a "SearchedIn" result, which details where we attempted to load a file from. This is then printed in error messages.
- Refactor some common library loading code into `Frontend.Driver` from the LSP server and main compiler driver.
Example output:
```
tests/amc/files/import.ml[1:6 ..1:23]: error (E1010)
Cannot resolve "my_lib.ml"
│ 
1 │ open import "my_lib.ml"
│      ^^^^^^^^^^^^^^^^^^
Searched in:
• /home/squiddev/programming/amulet/lib/my_lib.ml
• /home/squiddev/programming/amulet/.stack-work/blah/blugh/lib/my_lib.ml
• /home/squiddev/programming/amulet/.stack-work/blah/lib/my_lib.ml
```
=> Include the library path on missing imports

bin/Amc/Repl/Eval.hs, bin/AmuletLsp/Worker.hs, src/Frontend/Driver.hs, src/Syntax/Builtin.hs, src/Syntax/Implicits.hs, src/Syntax/Types.hs, src/Types/Infer.hs, src/Types/Infer/App.hs, src/Types/Infer/Class.hs, src/Types/Infer/Class.hs-boot, src/Types/Infer/Function.hs, tests/types/class/modules.ml, tests/types/class/modules.out, tests/types/letopen.out, tests/types/tyfun-scope.ml, tests/types/tyfun-scope.out
This removes the notion of a "module scope" within the type checker. Instead of our funky scope extension code, we just do a standard union.
This fixes the following issues:
- Type classes not being available until the module is opened (#232)
- Type classes duplicating when opening a module.
- Type functions not merging equations on opens/imports.
=> Simplify the module importing code

amuletml.cabal, doc/errors.txt, doc/errors/verify/3010.txt, doc/errors/verify/3011.txt, lib/amulet/base/intrinsics.ml, lib/amulet/base/lua.ml, src/Backend/Lua/Emit.hs, src/Core/Arity.hs, src/Core/Core.hs, src/Core/Intrinsic.hs, src/Core/Lower.hs, src/Core/Optimise/CommonExpElim.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Reduce.hs, src/Core/Optimise/Reduce/Base.hs, src/Core/Optimise/Reduce/Fold.hs, src/Core/Optimise/Reduce/Inline.hs, src/Core/Optimise/Sinking.hs, src/Syntax/Builtin.hs, src/Syntax/Verify.hs, src/Syntax/Verify/Error.hs, tests/lua/opt_constant_fold.lua, tests/lua/opt_constant_fold.ml, tests/verify/intrinsic.ml, tests/verify/intrinsic.out
- Add support for "intrinsics" (see #205) to Core. These are just written as foreign bindings, prefixed with a `%` (e.g. `external val ( + ) : int -> int -> int = "%int.add"`).
- Verify checks intrinsics exist and have the correct type.
- Adds back the constant folding pass removed in #184.
=> Constant folding, again
