examples/church-lists.ml, examples/skolems.ml, src/Control/Monad/Infer.hs, src/Core/Lower.hs, src/Core/Optimise.hs, src/Core/Optimise/Inline.hs, src/Core/Simplify.hs, src/Errors.hs, src/Syntax.hs, src/Syntax/Raise.hs, src/Syntax/Resolve.hs, src/Syntax/Subst.hs, src/Types/Infer.hs, src/Types/Kinds.hs, src/Types/Unify.hs, src/Types/Wellformed.hs
I'm not sure if these are sound, but cursory inspection at least tells me they're half logical.
I'm requesting a review from myself as well since it's past midnight and I have no idea if this code actually works or not.
=> Skolem Type Constants

src/Backend/Lua.hs, src/Control/Monad/Infer.hs, src/Data/Span.hs, src/Errors.hs, src/Pretty.hs, src/Syntax.hs
This means we no longer have to hide imports
=> Improve Pretty

examples/ambiguity.ml, src/Errors.hs, src/Syntax/Resolve.hs, src/Syntax/Resolve/Scope.hs
Because I'm incapable of actually working on what's needed.
=> Detect ambiguous references in the resolver

src/Backend/Compile.hs, src/Core/Core.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Fold.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Match.hs, src/Core/Optimise/Reduce.hs, src/Core/Simplify.hs, src/Core/Types.hs, src/Main.hs, src/Pretty.hs
=> No Co- Prefix

amuletml.cabal, compiler/Errors.hs, compiler/Main.hs, default.nix, src/Control/Monad/Infer.hs, src/Core/Occurrence.hs, src/Pretty.hs, src/Syntax/Desugar.hs, src/Syntax/Resolve.hs
=> Re-do package structure for tests

src/Backend/Compile.hs, src/Core/Core.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Inline.hs, src/Core/Optimise/Newtype.hs, src/Core/Optimise/Reduce.hs, src/Core/Types.hs, src/Syntax/Let.hs
Why did we do this again? Oh, right, join points.
=> Refactor Core bindings

compiler/Main.hs, src/Backend/Compile.hs, src/Core/Core.hs, src/Core/Occurrence.hs, src/Data/VarMap.hs
See the commit messages for a description. This should allow us to implement some more powerful passes.
=> Better occurrence checking

src/Control/Monad/Infer.hs, src/Types/Infer.hs, src/Types/Unify.hs
We do this by introducing a new type of constraint, ConFail Var Type,
which indicates that solving should stop here and return a FoundHole
error. Eek.
=> Handle typed holes in solver

compiler/Errors.hs, compiler/Main.hs, src/Syntax/Resolve.hs, src/Syntax/Resolve/Scope.hs, src/Types/Infer.hs
So my editor decides that "very" is a weasel word, so here we are.
=> Add a rather* primitive multi-file support, old chap

src/Control/Monad/Infer.hs, src/Core/Core.hs, src/Core/Lower.hs, src/Core/Optimise.hs, src/Core/Optimise/Reduce.hs, src/Syntax.hs, src/Syntax/Desugar.hs, src/Syntax/Let.hs, src/Syntax/Pretty.hs, src/Syntax/Raise.hs, src/Syntax/Resolve.hs, src/Syntax/Subst.hs, src/Types/Holes.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Constructor.hs, src/Types/Kinds.hs, src/Types/Unify.hs
I hate every single part of this, but it's nescessary.
=> Explicit evidence

amuletml.cabal, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Unify.hs
Oh boy is this ugly. But it's more efficient.
=> Use a custom transformer instead of everywhere

src/Core/Lower.hs, src/Parser.y, src/Syntax.hs, src/Syntax/Let.hs, src/Syntax/Pretty.hs, src/Syntax/Raise.hs, src/Syntax/Resolve.hs, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Pattern.hs
No major changes, but just lots of small ones across files.
=> Add literal patterns

examples/gadt/vector.ml, src/Control/Monad/Infer.hs, src/Core/Lower.hs, src/Parser.y, src/Syntax.hs, src/Syntax/Pretty.hs, src/Syntax/Raise.hs, src/Syntax/Resolve.hs, src/Syntax/Subst.hs, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Infer/Errors.hs, src/Types/Kinds.hs, src/Types/Unify.hs, src/Types/Wellformed.hs
Currently a bit silly. I'll tell you when it isn't.
=> Assume type : type and add promoted TyCons

src/Core/Core.hs, src/Core/Lint.hs, src/Core/Lower.hs, src/Syntax.hs, src/Syntax/Let.hs, src/Syntax/Pretty.hs, src/Syntax/Resolve.hs, src/Syntax/Transform.hs, src/Types/Infer.hs, src/Types/Infer/Pattern.hs, tests/gadt/gadt09-pass.ml, tests/gadt/gadt09-pass.out, tests/gadt/pass_vector.out
This is, frankly, a hack I pulled out of my ass, but I'd like for that test to work. And it does. So that's good.
=> Store wrappers in patterns

.hlint.yaml, .travis.yml, compiler/Repl/Display.hs, compiler/Test/Syntax/Gen.hs, compiler/Test/Types/Util.hs, default.nix, src/Backend/Lua/Emit.hs, src/Core/Free.hs, src/Core/Lower.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Syntax/Pretty.hs, src/Syntax/Verify.hs, src/Types/Infer.hs, src/Types/Infer/Builtin.hs, src/Types/Kinds.hs, src/Types/Unify.hs
Lets see how much this hurts build times.
=> Run HLint as part of the CI process

src/Syntax/Desugar.hs, src/Syntax/Expr/Instances.hs, src/Syntax/Verify.hs, src/Syntax/Verify/Error.hs, src/Text/Pretty/Note.hs, tests/lua/as_pattern.lua, tests/lua/opt_single_match.lua, tests/verify/match_to.ml, tests/verify/match_to.out, tests/verify/pmcheck/empty_match_03.ml, tests/verify/pmcheck/empty_match_03.out
There's some pretty gross stuff going on here due to `function` being desugared away. But it works, I guess??
=> Quick POC for suggesting you convert matches to functions.

.travis.yml, bin/Amc.hs, bin/Amc/Repl.hs, editor/amulet.vim, src/Backend/Lua.hs, src/Backend/Lua/Emit.hs, src/Backend/Lua/Postprocess.hs, src/Core/Occurrence.hs, src/Core/Optimise.hs, src/Core/Optimise/DeadCode.hs, src/Core/Optimise/Reduce.hs, src/Core/Simplify.hs, src/Parser/Context.hs, src/Syntax/Resolve/Scope.hs, tests/amc/export.t, tests/amc/files/export.ml, tests/amc/usage.t, tests/driver/Test/Core/Backend.hs, tests/driver/Test/Core/Lint.hs, tests/driver/Test/Types/Check.hs
Use --export to return any variables which are exported from the current program. This will also suppress DCE on these terms.
Closes #195
=> Allow generating Lua modules as well as programs

Jenkinsfile, deploy-build.sh, tests/driver/Test/Tasty/Reporter.hs
[here](https://callisto.amulet.works)
=> WIP: Build with Jenkins

tests/driver/Test/Tasty/Reporter.hs
=> Try to make verbose mode a little more informative (and pretty)

amuletml.cabal, bin/Amc.hs, bin/Amc/Repl.hs, src/Control/Timing.hs, src/Frontend/Driver.hs, tests/amc/usage.t, tools/quickinstall.sh
The driver can do IO, and IO can do timing, and so the driver can do timing.
=> Self-timing amc

lib/amulet/either.ml, lib/data/foldable.ml, lib/data/traversable.ml, lib/prelude.ml
I tried my best to obtain feature parity with the instances `option` has-- let me know if I missed anything.
=> Implement the "either" type.

bin/GenExample.hs
This must be merged _after_ amuletml/website#1.
=> Use CSS grid in examples instead

examples/amulet-logo.ml, examples/class/lens.ml, examples/class/quantified.ml, examples/coroutines.ml, examples/gadt/term.ml, examples/gadt/vector.ml, examples/guess.ml, examples/id.ml, examples/lazy-list.ml, examples/lists.ml, examples/modules.ml, examples/peano.ml, examples/pipe.ml, examples/polymorphic-recursion.ml, lib/amulet/base/lua.ml, lib/amulet/list.ml, lib/data/foldable.ml, tests/driver/Test/Core/Lint.hs
- Error if they produce any warnings at all. We want them to work after all!
- Depend on the prelude, rather than rolling our own everywhere. This will increase test times, so worth discussing if this is acceptable.
- A wee bit of cleanup in places.
=> Clean up the examples a little bit

bin/Amc.hs, bin/Amc/Compile.hs, bin/Amc/Explain.hs, bin/Amc/Repl/Command.hs, bin/Amc/Repl/Eval.hs, bin/GenExample.hs, src/Frontend/Errors.hs, tests/amc/prelude.t, tests/driver/Test/Core/Lint.hs
This has been irking me for a while, and someone filed an issue so I added it. Fixes #276.
=> Add :explain command to the repl
